default:
    app:
        twitter:
            accessToken: ACCESS_TOKEN
            accessTokenSecret: ACCESS_TOKEN_SECRET
            consumerKey: CONSUMER_KEY
            consumerSecret: CONSUMER_SECRET
    db:
        host: IP_ADRESSE
        port: PORT
        database: DATABASE_NAME